# Sentiment Analysis of Movie Reviews using TextBlob
This notebook demonstrates sentiment analysis on 5 movie reviews using TextBlob.

In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
!pip install textblob

Requirement already satisfied: textblob in c:\users\acer\anaconda3\lib\site-packages (0.20.1)
Requirement already satisfied: nltk>=3.9 in c:\users\acer\anaconda3\lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in c:\users\acer\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in c:\users\acer\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\acer\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\acer\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\acer\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ACER\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ACER\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\ACER\anaconda3\Lib\site-packages)

In [3]:
import pandas as pd
from textblob import TextBlob

In [5]:
# data={
# 'Review':[
# 'I loved this movie, it was fantastic!',
# 'Worst movie ever. Waste of time.',
# 'The movie was okay, not great not bad.',
# 'Excellent acting and a wonderful story.',
# 'I did not like the movie at all.'
# ]}
# df=pd.DataFrame(data)
# df

In [4]:
# df = pd.read_csv('/content/drive/MyDrive/NLP/movie_review.csv')
# df.head()

df = pd.read_csv('movie_review.csv')
df.head()

  Movie_Name                                           Review
0   Avengers    Amazing movie with outstanding action scenes.
1   Avengers  The story was emotional and very well executed.
2   Avengers             Best superhero movie I have watched.
3   Avengers             Excellent visual effects and acting.
4   Avengers                I loved every minute of the film.

## Get Polarity and Subjectivity

In [5]:
def get_sentiment(text):
    blob=TextBlob(text)
    return blob.sentiment.polarity, blob.sentiment.subjectivity

df[['Polarity','Subjectivity']]=df['Review'].apply(
    lambda x: pd.Series(get_sentiment(x))
)
df

,Movie_Name,Review,Polarity,Subjectivity
0,Avengers,Amazing movie with outstanding action scenes.,0.400000,0.625000
1,Avengers,The story was emotional and very well executed.,0.100000,0.475000
2,Avengers,Best superhero movie I have watched.,1.000000,0.300000
3,Avengers,Excellent visual effects and acting.,0.333333,0.333333
4,Avengers,I loved every minute of the film.,0.700000,0.800000
5,Avengers,The movie was too long and boring at times.,-0.525000,0.700000
6,Avengers,Average storyline but good action.,0.216667,0.366667
7,Avengers,Fantastic ending that made me emotional.,0.200000,0.775000
8,Avengers,Not as good as expected.,0.300000,0.500000
9,Avengers,Great performances by all the actors.,0.800000,0.750000
10,Three Idiots,Very inspiring and motivational movie.,0.650000,1.000000
11,Three Idiots,One of the best educational films ever made.,0.625000,0.275000
12,Three Idiots,"Funny, emotional, and meaningful.",0.250000,0.716667
13,Three Idiots,The movie teaches important life lessons.,0.400000,1.000000
14,Three Idiots,Superb acting and excellent screenplay.,0.666667,0.666667
15,Three Idiots,It was okay but a little lengthy.,0.156250,0.500000
16,Three Idiots,Some scenes were boring.,-1.000000,1.000000
17,Three Idiots,I enjoyed every scene of this movie.,0.500000,0.700000
18,Three Idiots,Brilliant direction and storytelling.,0.900000,1.000000
19,Three Idiots,Average movie with a predictable ending.,-0.175000,0.450000
20,Pushpa,Fantastic performance by the lead actor.,0.400000,0.900000
21,Pushpa,The songs and action scenes were amazing.,0.350000,0.500000
22,Pushpa,Excellent entertainment from start to finish.,1.000000,1.000000
23,Pushpa,I loved the background music.,0.700000,0.800000
24,Pushpa,The dialogues were powerful and memorable.,0.400000,1.000000
25,Pushpa,The story could have been better.,0.500000,0.500000
26,Pushpa,It was an average movie overall.,-0.075000,0.200000
27,Pushpa,Too much violence for my liking.,0.200000,0.200000
28,Pushpa,Great cinematography and visuals.,0.800000,0.750000
29,Pushpa,Worth watching with friends and family.,0.300000,0.100000

## Convert Polarity to Sentiment Label

In [6]:
def get_label(score):
    if score>0:
        return 'Positive'
    elif score<0:
        return 'Negative'
    else:
        return 'Neutral'

df['Sentiment']=df['Polarity'].apply(get_label)
df

,Movie_Name,Review,Polarity,Subjectivity,Sentiment
0,Avengers,Amazing movie with outstanding action scenes.,0.400000,0.625000,Positive
1,Avengers,The story was emotional and very well executed.,0.100000,0.475000,Positive
2,Avengers,Best superhero movie I have watched.,1.000000,0.300000,Positive
3,Avengers,Excellent visual effects and acting.,0.333333,0.333333,Positive
4,Avengers,I loved every minute of the film.,0.700000,0.800000,Positive
5,Avengers,The movie was too long and boring at times.,-0.525000,0.700000,Negative
6,Avengers,Average storyline but good action.,0.216667,0.366667,Positive
7,Avengers,Fantastic ending that made me emotional.,0.200000,0.775000,Positive
8,Avengers,Not as good as expected.,0.300000,0.500000,Positive
9,Avengers,Great performances by all the actors.,0.800000,0.750000,Positive
10,Three Idiots,Very inspiring and motivational movie.,0.650000,1.000000,Positive
11,Three Idiots,One of the best educational films ever made.,0.625000,0.275000,Positive
12,Three Idiots,"Funny, emotional, and meaningful.",0.250000,0.716667,Positive
13,Three Idiots,The movie teaches important life lessons.,0.400000,1.000000,Positive
14,Three Idiots,Superb acting and excellent screenplay.,0.666667,0.666667,Positive
15,Three Idiots,It was okay but a little lengthy.,0.156250,0.500000,Positive
16,Three Idiots,Some scenes were boring.,-1.000000,1.000000,Negative
17,Three Idiots,I enjoyed every scene of this movie.,0.500000,0.700000,Positive
18,Three Idiots,Brilliant direction and storytelling.,0.900000,1.000000,Positive
19,Three Idiots,Average movie with a predictable ending.,-0.175000,0.450000,Negative
20,Pushpa,Fantastic performance by the lead actor.,0.400000,0.900000,Positive
21,Pushpa,The songs and action scenes were amazing.,0.350000,0.500000,Positive
22,Pushpa,Excellent entertainment from start to finish.,1.000000,1.000000,Positive
23,Pushpa,I loved the background music.,0.700000,0.800000,Positive
24,Pushpa,The dialogues were powerful and memorable.,0.400000,1.000000,Positive
25,Pushpa,The story could have been better.,0.500000,0.500000,Positive
26,Pushpa,It was an average movie overall.,-0.075000,0.200000,Negative
27,Pushpa,Too much violence for my liking.,0.200000,0.200000,Positive
28,Pushpa,Great cinematography and visuals.,0.800000,0.750000,Positive
29,Pushpa,Worth watching with friends and family.,0.300000,0.100000,Positive

In [7]:
movie = input("Enter Movie Name: ")

movie_df = df[df["Movie_Name"].str.lower() == movie.lower()]


total_reviews = len(movie_df)

print("\nMovie Name:", movie)
print("Total Reviews:", total_reviews)

positive = len(movie_df[movie_df["Sentiment"] == "Positive"])
negative = len(movie_df[movie_df["Sentiment"] == "Negative"])
neutral = len(movie_df[movie_df["Sentiment"] == "Neutral"])

print(f"Positive : {positive} ({positive/total_reviews*100:.2f}%)")
print(f"Negative : {negative} ({negative/total_reviews*100:.2f}%)")
print(f"Neutral  : {neutral} ({neutral/total_reviews*100:.2f}%)")

Enter Movie Name:  Pushpa

Movie Name: Pushpa
Total Reviews: 10
Positive : 9 (90.00%)
Negative : 1 (10.00%)
Neutral  : 0 (0.00%)